import About from "@/components/About";
import Banner from "@/components/Banner";
import FeedbackCustomer from "@/components/FeedbackCustomer";
import Industry from "@/components/Industry";
import Newsletter from "@/components/Newsletter";
import Services from "@/components/Services";
import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>BCC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner
        title={"BCCCOMPANY with Vietnam business"}
        description={
          "Combining CRO expertise with world-class landing page technology, BCCCOMPANY helps businesses increase their digital advertising results with relevant, conversion-optimized landing pages for all of their campaigns"
        }
        isInput
        srcImage={"/assets/image-banner-home.png"}
        bgColor={`bg-gradient-to-r from-[#D8F3F7] via-[#D9E5F9] to-[#D7C6FD]`}
      />
      <Industry />
      <About />
      <Services />
      <div className="hidden lg:block lg:mb-20">
        <Image
          src="assets/curve_home1-wave.svg"
          alt=""
          height={158}
          width={0}
          className="w-full"
        />
      </div>
      <FeedbackCustomer />
      <Newsletter
        bgColor="bg-gradient-to-r from-[#90c5f1] via-[#90c5f1] to-[#ee8bab]"
        titleButton="Subscribe"
        description={
          "Stay in the know and be empowered with our strategic how-tos, resources, and guidelines."
        }
        title={"Get Helpful Tips And Info From Our Newsletter!"}
      />
    </>
  );
}
